version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - '5433:5432' 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs_cource

volumes:
  postgres_data:

networks:
  nestjs_cource: